version: "3"
services:
  nginx:
    image: nginx:stable-alpine3.17
    ports:
      - "80:80"
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
    restart: always
  node-app:
    build: .
    ports:
      - "3002:3000"
